"""empty message

Revision ID: 2a13c14562d5
Revises: 
Create Date: 2023-07-20 03:07:33.675171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a13c14562d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CardDetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_img', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_img', sa.Text(), nullable=True),
    sa.Column('card_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('duration_v', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('currency_v', sa.String(length=50), nullable=True),
    sa.Column('cashback', sa.String(length=50), nullable=True),
    sa.Column('cashback_v', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('text_bg', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CardOrder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('fin_code', sa.String(length=7), nullable=False),
    sa.Column('odenis_usulu', sa.String(length=255), nullable=False),
    sa.Column('secret_word', sa.String(length=30), nullable=False),
    sa.Column('elde_etme_usulu', sa.String(length=255), nullable=False),
    sa.Column('odenis_usulu2', sa.String(length=255), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['Cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CardOrder')
    op.drop_table('user')
    op.drop_table('Stories')
    op.drop_table('Cards')
    op.drop_table('CardDetails')
    # ### end Alembic commands ###
