"""empty message

Revision ID: 5d0b72f6a2d8
Revises: 6f9b05c33151
Create Date: 2023-07-21 22:01:03.736846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0b72f6a2d8'
down_revision = '6f9b05c33151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardDetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title2', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title3', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title4', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title5', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title6', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CardDetails', schema=None) as batch_op:
        batch_op.drop_column('title6')
        batch_op.drop_column('title5')
        batch_op.drop_column('title4')
        batch_op.drop_column('title3')
        batch_op.drop_column('title2')

    # ### end Alembic commands ###
