"""empty message

Revision ID: a725b6cffe61
Revises: 2a13c14562d5
Create Date: 2023-07-20 14:52:22.227157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a725b6cffe61'
down_revision = '2a13c14562d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Xeber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('desk', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Xeber')
    # ### end Alembic commands ###
